trigger:
- master

stages:
# ----------- Build Stage -----------
- stage: Build
  jobs:
    - job: BuildJob
      steps:
        

        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: 'JaCoCo'
            summaryFileLocation: 'target/site/jacoco/jacoco.xml'
            reportDirectory: 'target/site/jacoco'

       

# ----------- Deploy to Dev -----------
- stage: DeployDev
  dependsOn: Build
  jobs:
    - job: DeployDevJob
      steps:
        - download: current
          artifact: drop

        - script: |
            echo "Deploying to Dev on port 8081..."
            java -jar drop/DevOpsGroup4-0.0.1-SNAPSHOT.jar --server.port=8081
          displayName: 'Run App in Dev'

# ----------- Mock QAT, Staging, Prod -----------
- stage: QAT
  dependsOn: DeployDev
  jobs:
    - job: QATJob
      steps:
        - script: echo "Deployed to QAT"

- stage: Staging
  dependsOn: QAT
  jobs:
    - job: StagingJob
      steps:
        - script: echo "Deployed to Staging"

- stage: Production
  dependsOn: Staging
  jobs:
    - job: ProdJob
      steps:
        - script: echo "Deployed to Production"
