trigger:
- master

variables:
  buildConfiguration: 'Release'
  JAVA_HOME: 'C:\Program Files\Java\jdk-21'  

stages:
# ------------------------------
# CI - BUILD & TEST
# ------------------------------
- stage: Build
  displayName: 'Build and Test'
  jobs:
    - job: Build
      steps:
        - checkout: self

        - task: Maven@3
          displayName: 'Build with Maven'
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean install'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            mavenOptions: '-Xmx1024m'
            publishJUnitResults: true

        - task: PublishCodeCoverageResults@1
          displayName: 'Publish JaCoCo Code Coverage Report'
          inputs:
            codeCoverageTool: 'JaCoCo'
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
            reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'

        - script: echo $(JAVA_HOME)
          displayName: 'Check JAVA_HOME'

        - publish: $(System.DefaultWorkingDirectory)/target
          artifact: drop

# ------------------------------
# CD - DELIVER ARTIFACTS
# ------------------------------
- stage: Deliver
  displayName: 'Deliver Artifacts'
  dependsOn: Build
  jobs:
    - job: Deliver
      steps:
        - download: current
          artifact: drop

        - script: echo "Artifact delivered successfully to be used in deployment stages"
          displayName: 'Mock Deliver Step'

# ------------------------------
# CD - DEPLOY TO DEV
# ------------------------------
- stage: DeployToDev
  displayName: 'Deploy to Dev Environment'
  dependsOn: Deliver
  jobs:
    - job: DeployDev
      steps:
        - download: current
          artifact: drop

        - script: dir "$(Pipeline.Workspace)\drop" /s
          displayName: 'List artifact files'

        - script: |
            echo "Deploying to Dev Environment on port 8081"
            java -jar "$(Pipeline.Workspace)\drop\DevOpsGroup4-0.0.1-SNAPSHOT.jar" --server.port=8081 --spring.profiles.active=dev
          displayName: 'Run JAR on Port 8081'

# ------------------------------
# CD - DEPLOY TO QAT
# ------------------------------
- stage: DeployToQAT
  displayName: 'Deploy to QAT Environment'
  dependsOn: DeployToDev
  jobs:
    - job: DeployQAT
      steps:
        - script: echo "Mock deployment to QAT Environment"
          displayName: 'Deploy to QAT'

# ------------------------------
# CD - DEPLOY TO STAGING
# ------------------------------
- stage: DeployToStaging
  displayName: 'Deploy to Staging Environment'
  dependsOn: DeployToQAT
  jobs:
    - job: DeployStaging
      steps:
        - script: echo "Mock deployment to Staging Environment"
          displayName: 'Deploy to Staging'

# ------------------------------
# CD - DEPLOY TO PRODUCTION
# ------------------------------
- stage: DeployToProduction
  displayName: 'Deploy to Production Environment'
  dependsOn: DeployToStaging
  jobs:
    - job: DeployProd
      steps:
        - script: echo "Mock deployment to Production Environment"
          displayName: 'Deploy to Production'
